"""Chaos rig: throws messy real-world inputs at maclookup.lookup_detailed
and reports how well each scenario is handled.

Usage
-----
::

    python3 tests/chaos_rig.py                    # plain text report to stdout
    python3 tests/chaos_rig.py --md               # Markdown report to stdout
    python3 tests/chaos_rig.py --md --out F.md    # write Markdown to F.md
    python3 tests/chaos_rig.py --strict           # exit 1 if any case mismatches

The rig is also exercised by ``tests/test_chaos_rig.py`` as part of the
unittest suite so CI fails if the corpus' assertions drift from
``lookup_detailed`` behavior. The Markdown snapshot lives at
``tests/fixtures/chaos_report.md`` and is regenerated by running
``python3 tests/chaos_rig.py --md --out tests/fixtures/chaos_report.md``.
"""
from __future__ import annotations

import argparse
import importlib.util
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_PATH = REPO_ROOT / "maclookup.py"


def _load_maclookup():
    spec = importlib.util.spec_from_file_location("maclookup", SCRIPT_PATH)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["maclookup"] = mod
    spec.loader.exec_module(mod)
    return mod


# Late import so the corpus and the runner can share types.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from chaos_corpus import CASES, Case  # noqa: E402


@dataclass
class Outcome:
    case: Case
    classified: str           # "match" | "match_ocr" | "partial" | "none"
    cleaned: Optional[str]
    record_assignment: Optional[str]
    record_registry: Optional[str]
    organization: Optional[str]
    passed: bool
    reason: str               # empty when passed

    @property
    def display_input(self) -> str:
        return self.case.input.replace("\n", "\\n").replace("\t", "\\t")


def classify(result) -> str:
    """Map a LookupResult to one of the four expectation classes."""
    if result.record is not None:
        return "match_ocr" if result.note == "ocr" else "match"
    if result.cleaned is not None:
        return "partial"
    return "none"


def evaluate(case: Case, result) -> Outcome:
    cls = classify(result)
    record_assignment = result.record.assignment if result.record else None
    record_registry = result.record.registry if result.record else None
    organization = result.record.organization if result.record else None

    passed = True
    reason = ""

    # The two 'match' classes are interchangeable in one direction: a clean
    # match satisfies an OCR expectation only if the corpus didn't pin
    # something stricter. Conversely an OCR match never satisfies a 'match'
    # expectation (we want clean inputs to take the clean path).
    if case.expect == "match" and cls == "match_ocr":
        passed = False
        reason = "expected clean match but got OCR-corrected match"
    elif case.expect != cls and not (case.expect == "match_ocr" and cls == "match"):
        # match_ocr-expected can be satisfied by a clean match when the
        # underlying token happened to be valid even without OCR; otherwise
        # this is a mismatch.
        passed = False
        reason = f"expected {case.expect!r}, classified as {cls!r}"

    if passed and case.assignment is not None:
        if record_assignment != case.assignment:
            passed = False
            reason = (
                f"expected assignment={case.assignment!r}, "
                f"got={record_assignment!r}"
            )

    if passed and case.cleaned is not None and result.cleaned != case.cleaned:
        passed = False
        reason = (
            f"expected cleaned={case.cleaned!r}, got={result.cleaned!r}"
        )

    return Outcome(
        case=case,
        classified=cls,
        cleaned=result.cleaned,
        record_assignment=record_assignment,
        record_registry=record_registry,
        organization=organization,
        passed=passed,
        reason=reason,
    )


def run(cases: list[Case]) -> list[Outcome]:
    maclookup = _load_maclookup()
    registries = maclookup.load_all()
    outcomes: list[Outcome] = []
    for case in cases:
        result = maclookup.lookup_detailed(case.input, registries)
        outcomes.append(evaluate(case, result))
    return outcomes


def _fmt_input(s: str, limit: int = 80) -> str:
    s = s.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r")
    return s if len(s) <= limit else s[: limit - 1] + "…"


def _summary(outcomes: list[Outcome]) -> dict:
    by_class = Counter(o.classified for o in outcomes)
    by_expect = Counter(o.case.expect for o in outcomes)
    by_category = defaultdict(lambda: [0, 0])
    for o in outcomes:
        by_category[o.case.category][0] += 1
        by_category[o.case.category][1] += int(o.passed)
    return {
        "total": len(outcomes),
        "passed": sum(1 for o in outcomes if o.passed),
        "failed": sum(1 for o in outcomes if not o.passed),
        "by_class": dict(by_class),
        "by_expect": dict(by_expect),
        "by_category": {k: tuple(v) for k, v in by_category.items()},
    }


def format_text(outcomes: list[Outcome]) -> str:
    s = _summary(outcomes)
    lines = []
    lines.append(f"chaos rig: {s['passed']}/{s['total']} passed, {s['failed']} failed")
    lines.append("")
    lines.append("by classification:")
    for k in ("match", "match_ocr", "partial", "none"):
        lines.append(f"  {k:<10} {s['by_class'].get(k, 0)}")
    lines.append("")
    lines.append("by category (passed/total):")
    for cat, (total, passed) in sorted(s["by_category"].items()):
        lines.append(f"  {cat:<14} {passed}/{total}")
    fails = [o for o in outcomes if not o.passed]
    if fails:
        lines.append("")
        lines.append("FAILURES:")
        for o in fails:
            lines.append(f"  [{o.case.category}] {_fmt_input(o.case.input)}")
            lines.append(f"      {o.reason}")
    return "\n".join(lines)


def format_markdown(outcomes: list[Outcome]) -> str:
    s = _summary(outcomes)
    out: list[str] = []
    out.append("# MAC lookup chaos rig — report")
    out.append("")
    out.append(
        "This file is generated by `tests/chaos_rig.py --md`. It is a "
        "snapshot of how `maclookup.lookup_detailed` handles a corpus of "
        "messy real-world inputs (Windows ipconfig / Linux ip-link / "
        "Cisco show / BIOS / OCR / multi-line pastes / Unicode / etc.)."
    )
    out.append("")
    out.append(
        f"**Result:** {s['passed']} / {s['total']} cases match expectations "
        f"({s['failed']} mismatch)."
    )
    out.append("")
    out.append("## Counts by classification")
    out.append("")
    out.append("| outcome | count |")
    out.append("| --- | ---: |")
    for k in ("match", "match_ocr", "partial", "none"):
        out.append(f"| {k} | {s['by_class'].get(k, 0)} |")
    out.append("")
    out.append("## Counts by category")
    out.append("")
    out.append("| category | passed / total |")
    out.append("| --- | ---: |")
    for cat, (total, passed) in sorted(s["by_category"].items()):
        out.append(f"| {cat} | {passed} / {total} |")
    out.append("")

    fails = [o for o in outcomes if not o.passed]
    if fails:
        out.append("## Mismatches")
        out.append("")
        out.append("| input | expected | got | reason |")
        out.append("| --- | --- | --- | --- |")
        for o in fails:
            out.append(
                f"| `{_fmt_input(o.case.input)}` | {o.case.expect} | "
                f"{o.classified} | {o.reason} |"
            )
        out.append("")
    else:
        out.append("## Mismatches")
        out.append("")
        out.append("None. Every case in the corpus matched its expected outcome.")
        out.append("")

    # Detail table — every case, grouped by category, so reviewers can see
    # the corpus and the actual behavior side by side.
    out.append("## Detailed results")
    out.append("")
    by_cat: dict[str, list[Outcome]] = defaultdict(list)
    for o in outcomes:
        by_cat[o.case.category].append(o)
    for cat in sorted(by_cat):
        out.append(f"### {cat}")
        out.append("")
        out.append("| input | expected | got | cleaned | record | note |")
        out.append("| --- | --- | --- | --- | --- | --- |")
        for o in by_cat[cat]:
            record = ""
            if o.record_registry and o.record_assignment:
                record = f"{o.record_registry} {o.record_assignment}"
                if o.organization:
                    record += f" — {o.organization[:40]}"
            out.append(
                "| `{inp}` | {exp} | {got} | {cleaned} | {rec} | {note} |".format(
                    inp=_fmt_input(o.case.input, limit=60),
                    exp=o.case.expect,
                    got=o.classified,
                    cleaned=o.cleaned or "",
                    rec=record,
                    note=o.case.note,
                )
            )
        out.append("")
    return "\n".join(out)


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--md", action="store_true", help="emit Markdown report")
    p.add_argument("--out", type=Path, help="write report to this file instead of stdout")
    p.add_argument("--strict", action="store_true",
                   help="exit non-zero if any case mismatches")
    args = p.parse_args(argv)

    outcomes = run(CASES)
    text = format_markdown(outcomes) if args.md else format_text(outcomes)

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text + "\n", encoding="utf-8")
    else:
        print(text)

    if args.strict and any(not o.passed for o in outcomes):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
